---

- name: install the latest version of memcached
  yum: name=memcached state=latest

- name: configure  firewalld policy
  firewalld: port={{ item }}/tcp permanent=true state=enabled immediate=true
  loop: "{{ memcached_port }}"

- name: add memcached to systemd 
  systemd: name=memcached state=started enabled=yes masked=no
