---
- name: delete directory /etc/yum.repos.d/
  file: path=/etc/yum.repos.d/ state=absent

- name: create directory /etc/yum.repos.d/
  file: path=/etc/yum.repos.d/ state=directory owner=root group=root mode=0755

- name: copy server.repo to {{ inventory_hostname }}
  copy: src=server.repo dest=/etc/yum.repos.d/server.repo mode=0644 owner=root group=root force=yes
